### ISSUE TITLE
Example fails with Request error

### ISSUE THREAD

**Issue by jprctr** [topos-ai/tsi-network#2]
When attempting to run the example locally I see the following error in Chrome.

```Failed to load https://api.topos.ai/v1/public/region/us-zipcode/10002/similarities: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access.```

This example also no longer loads correctly at https://api.topos.ai/
![screen shot 2018-01-02 at 10 16 17 pm](https://user-images.githubusercontent.com/693555/34510686-073e402c-f00b-11e7-8c97-4524f76bd232.png)

Seems like the api response headers changed at some point?

**Comment by buth** [comment]
Looks like API is only allowing requests from "localhost" at the moment; I'll add "127.0.0.1" and update this issue. Thanks for the heads up!

**Comment by buth** [comment]
@jprctr This should be working now.

**Comment by jprctr** [comment]
That's perfect - now working for me on 127.0.0.1 and https://api.topos.ai/ - thanks for your help!
